# dbt_fleet_intel/dbt_project.yml
name: 'fleet_intel'
version: '1.0.0'
config-version: 2

# This is where dbt will look for SQL files
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

profile: 'fleet_intel' 

models:
  fleet_intel: 
    # This means everything in models/staging/ will be created as VIEWS in BigQuery
    staging:
      +materialized: view
    # This means everything in models/marts/ will be created as TABLES in BigQuery
    marts:
      +materialized: table
