fleet_intel:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: fleet_intel_staging
      # This points to the "Ghost File" we create in the workflow
      keyfile: "../service_account.json" 
      threads: 4
      location: US